### ISSUE TITLE
Multiple sub-/sections with the same name get assigned the same anchor target label

### ISSUE THREAD

**Issue by sabine** [ocaml/odoc#894]
When a page has multiple sections with the same name, the same anchor target label is used multiple times.

**Problem:** User cannot deep-link to the second "Examples" section, as clicking on the anchor tag will link to the first "Examples" section.

**Example:** There are two sections called "Examples" on https://ocaml.org/p/streaming/0.8.0/doc/index.html#examples

**Solution:** Make sure to not use the same label, e.g. assign #examples to the first "Examples" section, and #examples-2 to the second "Examples" section.

Chances are that this could be a simple issue for a first-time contributor.

**Comment by Julow** [comment]
This has been fixed in https://github.com/ocaml/odoc/pull/720
Perhaps it's a bug in the custom generator for ocaml.org, given that the check is done at the last stage of compilation. (maybe [this check](https://github.com/ocaml/odoc/pull/720/files#diff-6c455c2657c68cf89b442c7b3c19fef8503cf643a31ad0cb81d926d34e47ac10R380-R386) is missing)

**Comment by sabine** [comment]
Thanks, sorry about the spurious issue, then. Indeed, you're correct, ocaml.org is suffering from this problem still and it's great to see that this is not an upstream issue. :+1:
